version: "2"
services:
  cache-server-webflux:
    image: java:8
    container_name: java-cache-server-webflux
    restart: always
    working_dir: /root
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - ./cache-server/target/cache-server-1.0.0.jar:/root/app.jar
      - ./log:/root/
    privileged: true
    environment:
      - cache-server.hash-server-host=http://liangyuelong.com:8051/
      - memcached.servers=139.9.142.248:11211
      - hash.pool.core-size=20
    command: java -jar /root/app.jar -Xms320m -Xmx320m > /root/spring.log
  cache-server-webmvc:
    image: java:8
    container_name: java-cache-server-webmvc
    restart: always
    working_dir: /root
    network_mode: bridge
    ports:
      - 8080:8080
    volumes:
      - ./cache-server-webmvc/target/cache-server-webmvc-1.0.0.jar:/root/app.jar
      - ./log:/root/
    privileged: true
    environment:
      - cache-server.hash-server-host=http://liangyuelong.com:8051/
      - memcached.servers=139.9.142.248:11211
      - hash.pool.core-size=20
    command: java -jar /root/app.jar -Xms320m -Xmx320m > /root/spring.log
