version: "3"
services:
  cache-server:
    image: java:8
    container_name: java-cache-server1
    restart: always
    working_dir: /root
    network_mode: bridge
    ports:
      - 6671:8080
    volumes:
      - ./cache-server-1.0.0.jar:/root/app.jar
      - ./spring.log:/root/spring.log
    privileged: true
    command:
      - java -jar
      - -Dcache-server.hash-server-host=server地址
      - -Dmemcached.servers=memcached地址
      - -Dhash.pool.core-size=20
      - /root/app.jar -Xms320m -Xmx320m
    mem_limit: 320m
